version: "3.8"

services:

  auth-service:
    image: lauracucu/auth-microservice:2
    environment:
      JWT_SECRET_KEY: myawesomeultrasecretkey
      JWT_ISSUER: student
      JWT_SUBJECT: 'Token pentru proiect'
      JWT_AUDIENCE: postman
      AUTH_SERVICE_API_ROUTE: bank-app_auth-service/api
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: bank-app_db
      PGPORT: 5432
      PGDATABASE: bank
      NODE_ENV: development
    networks:
      - internal
      - auth-db-network

  business-logic-service:
    image: lauracucu/business-logic-microservice:2
    environment:
      IO_SERVICE_API_ROUTE: bank-app_io-service/api
      AUTH_SERVICE_API_ROUTE: bank-app_auth-service/api
      NODE_ENV: development
    networks:
      - internal
      - business-logic-io-network

  io-service:
    image: lauracucu/io-microservices:2
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: bank-app_db
      PGPORT: 5432
      PGDATABASE: bank
      NODE_ENV: development
    networks:
      - business-logic-io-network
      - io-db-network

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - io-db-network
      - auth-db-network
      - db-adminer-network
    volumes:
      - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db-persistent-volume:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - db-adminer-network

  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - internal

volumes:
  db-persistent-volume:

networks:
  internal:
  business-logic-io-network:
  auth-db-network:
  io-db-network:
  db-adminer-network:
